name: cheapBuy
language: python
python:
  - "3.6"
  - "3.7"
addons:
  chrome: stable
before_install:
  - python -m pip install --upgrade pip
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
install:
  - pip install -r requirements.txt
before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
script:
  - cd test 
  - pytest 
