name: cheapBuy
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - python -m pip install --upgrade pip
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
install:
  - pip install -r requirements.txt
addons:
  chrome: stable
before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
script:
  - cd test 
  - pytest 
